#!/bin/bash


branch=`git rev-parse --abbrev-ref HEAD`
branchRegex='([A-Z_]+?)(-[0-9]+)'

if [[ $branch =~ $branchRegex ]]
then
  sed -i "1s/^/\n\n${BASH_REMATCH[1]}${BASH_REMATCH[2]}/" $1
fi

# Put in BASE_DIR/.git/hooks/prepare-commit-msg. Make executable
